version: '3.3'
services:
  enexa:
    build:
      context: .
      dockerfile: test-service.Dockerfile
    container_name: enexa
    image: enexa-test-service
    ports:
      - "36321:36321"
  fuseki:
    container_name: fuseki
    image: stain/jena-fuseki
    environment:
      ADMIN_PASSWORD: "admin"
      FUSEKI_DATASET_1: "test"
    ports:
      - "47238:3030"
