#!/bin/sh
set -eu
DIR="$(dirname "$(realpath "$0")")"/

FILE="$1"
PROPERTY="${2:-}"

case "$FILE" in
    "$ENEXA_SHARED_DIRECTORY"*)
        TARGET="$FILE"
        ;;
    *)
        mkdir -p "$ENEXA_MODULE_INSTANCE_DIRECTORY"
        TARGET=$(mktemp --tmpdir="$ENEXA_MODULE_INSTANCE_DIRECTORY" --suffix ".$(basename "$FILE")" XXXXXXXXXX)
        cp "$FILE" "$TARGET"
        ;;
esac

NAME=$(echo "$TARGET" |perl -pe '$q = quotemeta $ENV{ENEXA_SHARED_DIRECTORY}; s/$q//')

RESOURCE_URI=$(curl \
    -s \
    -o /dev/null --dump-header - \
    -X POST \
    "$ENEXA_SERVICE_URL"add-resource \
    |awk '/^Content-Location: / { sub(/^[^:]+: /, ""); print }' |tr -d $'\r')

PROPERTY_TRIPLES=""
if [ ! -z "$PROPERTY" ]; then
    PROPERTY_TRIPLES="<$ENEXA_MODULE_INSTANCE_IRI> <$PROPERTY> <$RESOURCE_URI> ."
fi

echo "PREFIX enexa: <http://w3id.org/dice-research/enexa/ontology#> INSERT DATA { <$RESOURCE_URI> enexa:location 'enexa-dir:/$NAME' . $PROPERTY_TRIPLES }" \
     |"$DIR"/sparql-update "$ENEXA_META_DATA_ENDPOINT"

echo "$RESOURCE_URI"
