#!/bin/sh
set -eu
DIR="$(dirname "$(realpath "$0")")"/

ENEXA_PARAMETER_IRI="$1"

echo "SELECT ?v { <$ENEXA_MODULE_INSTANCE_IRI> <$ENEXA_PARAMETER_IRI> ?v }" \
|"$DIR"/sparql-select "$ENEXA_META_DATA_ENDPOINT" \
|awk '(NR==2) { gsub(/^"|"$/, ""); print }'
