#!/bin/sh
set -eu
DIR="$(dirname "$(realpath "$0")")"/

FILE="$1"

TARGET=$(mktemp --tmpdir="$ENEXA_WRITEABLE_DIRECTORY" --suffix ".$(basename "$FILE")" enexa.$(date +%s).XXXXXXXXXX)
cp "$FILE" "$TARGET"

NAME=$(echo "$TARGET" |perl -pe '$q = quotemeta $ENV{ENEXA_SHARED_DIRECTORY}; s/$q//')

RESOURCE_URI=$(curl \
    -s \
    -o /dev/null --dump-header - \
    -X POST \
    "$ENEXA_SERVICE_URL"add-resource \
    |awk '/^Content-Location: / { sub(/^[^:]+: /, ""); print }' |tr -d $'\r')

echo "PREFIX enexa: <http://w3id.org/dice-research/enexa/ontology#> INSERT DATA { <$RESOURCE_URI> enexa:location 'enexa-dir:/$NAME' }" \
     |"$DIR"/sparql-update "$ENEXA_META_DATA_ENDPOINT"

echo "$RESOURCE_URI"
