#!/bin/sh
OUTPUT=$(mktemp)

curl \
    --silent --show-error \
    --output "$OUTPUT" \
    --write-out "%{http_code}" \
    --data-urlencode "update@-" \
    --request POST "$1" \
    |grep -q '^200$'

RET=$?

if [ $RET -ne 0 ]; then
    cat $OUTPUT >&2
fi
exit $RET
