#!/usr/bin/env python3
from http.server import BaseHTTPRequestHandler, HTTPServer

class Handler(BaseHTTPRequestHandler):
    def do_POST(self):
        self.send_response(200)
        self.send_header('Content-Location', 'http://example.org/new-resource-iri')
        self.end_headers()

if __name__ == '__main__':
    HTTPServer(('127.0.0.1', 36321), Handler).serve_forever()
