#!/usr/bin/env python3
import time
from http.server import BaseHTTPRequestHandler, HTTPServer

class Handler(BaseHTTPRequestHandler):
    def do_POST(self):
        self.send_response(200)
        self.send_header('Content-Location', 'http://example.org/new-resource-iri-' + str(time.time_ns()))
        self.end_headers()

if __name__ == '__main__':
    HTTPServer(('0.0.0.0', 36321), Handler).serve_forever()
